# Generated by Django 4.0 on 2021-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeracks',
            name='surveillance_efficiency',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('RED', 'RED'), ('YELLOW', 'YELLOW')], default='RED', max_length=50),
        ),
    ]
